---
Name: CommerceBulkPrice
After: 'framework/*'
---
CatalogueProduct:
  extensions:
    - BulkPriceProduct
CatalogueProductController:
  extensions:
    - BulkPriceCatalogueController
ShoppingCart:
  extensions:
    - BulkPriceShoppingCart
ProductCSVBulkLoader:
  extensions:
    - BulkPriceProductCSV
