---
Name: CommerceBulkPrice
After: 'framework/*'
---
Product:
  extensions:
    - BulkPriceProduct
ShoppingCart:
  extensions:
    - BulkPriceShoppingCart
ProductCSVBulkLoader:
  extensions:
    - BulkPriceProductCSV
Catalogue_Controller:
  extensions:
    - BulkPriceCatalogueController
